apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acme-dns.fullname" . }}
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
data:
  config.cfg: |-
    {{ .Values.config | nindent 4 }}