apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.headless.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.ports.dnsTcp }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.ports.dnsUdp }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-api
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.api.type }}
  ports:
    - port: {{ .Values.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "acme-dns.fullname" . }}-01
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-dns
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.dns.type }}
  ports:
    - port: {{ .Values.ports.dnsTcp }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.ports.dnsUdp }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "acme-dns.fullname" . }}-01
