apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.services.api.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.services.dns.ports.dnsTcp }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.services.dns.ports.dnsUdp }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "acme-dns.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-api
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
    {{- with .Values.services.api.metadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.services.api.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.api.type }}
  ports:
    - port: {{ .Values.services.api.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "acme-dns.fullname" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-dns.fullname" . }}-dns
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
    {{- with .Values.services.dns.metadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.services.dns.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.dns.type }}
  ports:
    - port: {{ .Values.services.dns.ports.dnsTcp }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.services.dns.ports.dnsUdp }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "acme-dns.fullname" . }}-0
